#!/bin/sh

echo 'Creating ORDERS table in CDB'

sqlplus C\#\#MYUSER/mypassword@//localhost:1521/ORCLCDB  <<- EOF

  create table ORDERS (
          order_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 42) NOT NULL PRIMARY KEY,
          customer_id VARCHAR(10),
          order_total_usd VARCHAR(50),
          make VARCHAR(50),
          model VARCHAR(50),
          delivery_company VARCHAR(50),
          delivery_address VARCHAR(50),
          delivery_city VARCHAR(50),
          delivery_state VARCHAR(50),
          delivery_zip VARCHAR(50),
          create_ts timestamp DEFAULT CURRENT_TIMESTAMP ,
          update_ts timestamp
  );

  CREATE OR REPLACE TRIGGER TRG_ORDERS_UPD
  BEFORE INSERT OR UPDATE ON ORDERS
  REFERENCING NEW AS NEW_ROW
    FOR EACH ROW
  BEGIN
    SELECT SYSDATE
          INTO :NEW_ROW.UPDATE_TS
          FROM DUAL;
  END;
  /

EOF

